### ISSUE TITLE
FAZ 2

### ISSUE THREAD

**Issue by uysalserkan** [uysalserkan/Tubitak_Project#20]
## Main Requirements

- [x] Dış kullanıcı, başvuru yapmış olduğu etkinlikleri listeler. #17 
- [x] Dış kullanıcı başlangıç tarihi geçmemiş olan tüm etkinlikleri listeler. (etkinlik adı, başlangıç tarihi, bitiş tarihi)
- [x] Dış kullanıcı etkinliğe başvurur. (adı soyad, tc kimlik no.) #14 
- [x] Her kayıt için bir QRcode üretilerek email ile gönderilir ve ekranda da gösterilir.
- [x] Dış kullanıcı kayıt olduğu zaman, oluşturulan QRcode ve katılım bilgileri ile dış kullanıcıya sistem mail göndermeli. #21 

## Extra Requirements

- [x] Aynı tc kimlik no. ile bir etkinliğe birden çok başvuru yapılamaz.
- [x] Bir işlem başarı ile tamamlandıktan sonra başarı mesajı gösterilir.
- [x] Bir işlemde hata alındığında hata mesajı gösterilir. 
- [x] Oluşturulan QRcode decode edildiğinde etkinlik ve katılımcı bilgileri görülebilecektir.
- [x] EventStatus eklenebilir.
- [x] Şu an aktif olan etkinlikler gösterilir.
